repos:
    - repo: local
      hooks:
          - id: fmt
            name: Formatter
            language: system
            types: [ts, yaml, json, markdown]
            entry: npm run fmt
            always_run: false
          - id: lint
            name: Lint
            language: system
            types: [ts]
            entry: npm run lint
            always_run: false
          - id: test
            name: Test
            language: system
            types: [ts]
            entry: npm test
            pass_filenames: false
            always_run: false
          - id: tsc
            name: Build
            language: system
            types: [ts]
            entry: npm run check
            pass_filenames: false
            always_run: false
